<a href="https://colab.research.google.com/github/abdurrahman16/Electricity-Demand-Forecasting_Model-XGboost-/blob/main/Electricity_Demand_Forecasting_Model(XGboost).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt #bar graph
%matplotlib inline
import seaborn as sns #visualization
import random #random values

In [ ]:
data=pd.read_csv('Electricity_Dataset.csv') #file import
data

,Timestamp,hour,dayofweek,month,year,dayofyear,Temperature,Humidity,Demand
0,01-Jan-20,0.0,2.0,1.0,2020.0,1.0,3.000000,61.288951,2457.119872
1,01-Jan-20,1.0,2.0,1.0,2020.0,1.0,3.000000,52.873702,2269.904712
2,01-Jan-20,2.0,2.0,1.0,2020.0,1.0,4.244482,36.341783,2215.640403
3,01-Jan-20,3.0,2.0,1.0,2020.0,1.0,3.000000,72.629378,2174.232413
4,01-Jan-20,4.0,2.0,1.0,2020.0,1.0,3.881208,90.582444,2472.453006
...,...,...,...,...,...,...,...,...,...
43843,31-Dec-24,19.0,1.0,12.0,2024.0,366.0,3.956838,43.287161,4689.693109
43844,31-Dec-24,20.0,1.0,12.0,2024.0,366.0,3.118824,51.705756,4331.249224
43845,31-Dec-24,21.0,1.0,12.0,2024.0,366.0,3.000000,40.565916,4015.979957
43846,31-Dec-24,22.0,1.0,12.0,2024.0,366.0,3.000000,51.998107,3353.241682
43847,31-Dec-24,23.0,1.0,12.0,2024.0,366.0,6.037472,59.931925,3219.023339

In [ ]:
data.info() #data information check

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43848 entries, 0 to 43847
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Timestamp    43848 non-null  object
 1   hour         43837 non-null  float64
 2   dayofweek    43839 non-null  float64
 3   month        43840 non-null  float64
 4   year         43843 non-null  float64
 5   dayofyear    43843 non-null  float64
 6   Temperature  43841 non-null  float64
 7   Humidity     43838 non-null  float64
 8   Demand       43841 non-null  float64
dtypes: float64(8), object(1)
memory usage: 3.0+ MB

In [9]:
data['Timestamp']= pd.to_datetime(data['Timestamp']) #timestamp object to datetime

In [10]:
data = data.set_index('Timestamp') #timestamp set as index

In [14]:
data[['Temperature','Humidity','Demand']].describe() #check the information on some columns

        Temperature      Humidity        Demand
count  43841.000000  43838.000000  43841.000000
mean      25.067788     59.903007   5000.790976
std       12.821725     18.342604   1412.527409
min        3.000000     20.000000   1611.954020
25%       15.210186     46.241224   4015.668472
50%       25.003212     59.986720   5013.053367
75%       34.740971     73.796820   6000.803082
max       50.000000     95.000000  11910.705100

In [37]:
#check missing values
data.isnull().sum()

hour           0
dayofweek      0
month          0
year           0
dayofyear      0
quarter        0
Temperature    0
Humidity       0
Demand         0
dtype: int64

In [28]:
#check where all the nun values are available
data[data.isnull().any(axis=1)]

Empty DataFrame
Columns: [hour, dayofweek, month, year, dayofyear, Temperature, Humidity, Demand]
Index: []

In [24]:
data[data.isnull().all(axis=1)] #find all the rows having null value

Empty DataFrame
Columns: [hour, dayofweek, month, year, dayofyear, Temperature, Humidity, Demand]
Index: []

In [19]:
#drop fully missing line
data=data.dropna(how='all')
#data[data.isnull().all(axis=1)]

Empty DataFrame
Columns: [hour, dayofweek, month, year, dayofyear, Temperature, Humidity, Demand]
Index: []

In [26]:
#use backward fill bfill or forward fill ffill || Dat Time index thakle(timeseries hole interpolate()) method use kora jabe

data[['hour', 'dayofweek', 'month', 'year', 'dayofyear', 'Temperature', 'Humidity', 'Demand']]=data[['hour', 'dayofweek', 'month', 'year', 'dayofyear', 'Temperature', 'Humidity', 'Demand']].ffill()

In [39]:
data.shape #check row column
#data.insert(5,'quarter',data.index.quarter) #insert quarter column
data

,hour,dayofweek,month,year,dayofyear,quarter,Temperature,Humidity,Demand
Timestamp,,,,,,,,,
2020-01-01,0.0,2.0,1.0,2020.0,1.0,1,3.000000,61.288951,2457.119872
2020-01-01,1.0,2.0,1.0,2020.0,1.0,1,3.000000,52.873702,2269.904712
2020-01-01,2.0,2.0,1.0,2020.0,1.0,1,4.244482,36.341783,2215.640403
2020-01-01,3.0,2.0,1.0,2020.0,1.0,1,3.000000,72.629378,2174.232413
2020-01-01,4.0,2.0,1.0,2020.0,1.0,1,3.881208,90.582444,2472.453006
...,...,...,...,...,...,...,...,...,...
2024-12-31,19.0,1.0,12.0,2024.0,366.0,4,3.956838,43.287161,4689.693109
2024-12-31,20.0,1.0,12.0,2024.0,366.0,4,3.118824,51.705756,4331.249224
2024-12-31,21.0,1.0,12.0,2024.0,366.0,4,3.000000,40.565916,4015.979957
2024-12-31,22.0,1.0,12.0,2024.0,366.0,4,3.000000,51.998107,3353.241682
2024-12-31,23.0,1.0,12.0,2024.0,366.0,4,6.037472,59.931925,3219.023339

In [42]:
data[['hour', 'dayofweek', 'month', 'year', 'dayofyear', 'Temperature', 'Humidity', 'Demand']]=data[['hour', 'dayofweek', 'month', 'year', 'dayofyear', 'Temperature', 'Humidity', 'Demand']].astype(int)
data

,hour,dayofweek,month,year,dayofyear,quarter,Temperature,Humidity,Demand
Timestamp,,,,,,,,,
2020-01-01,0,2,1,2020,1,1,3,61,2457
2020-01-01,1,2,1,2020,1,1,3,52,2269
2020-01-01,2,2,1,2020,1,1,4,36,2215
2020-01-01,3,2,1,2020,1,1,3,72,2174
2020-01-01,4,2,1,2020,1,1,3,90,2472
...,...,...,...,...,...,...,...,...,...
2024-12-31,19,1,12,2024,366,4,3,43,4689
2024-12-31,20,1,12,2024,366,4,3,51,4331
2024-12-31,21,1,12,2024,366,4,3,40,4015
2024-12-31,22,1,12,2024,366,4,3,51,3353
2024-12-31,23,1,12,2024,366,4,6,59,3219

In [44]:
#create week column
data.insert(5,'weekofyear',data.index.isocalendar().week.astype(int))

ValueError: cannot insert weekofyear, already exists

,hour,dayofweek,month,year,dayofyear,weekofyear,quarter,Temperature,Humidity,Demand
Timestamp,,,,,,,,,,
2020-01-01,0,2,1,2020,1,1,1,3,61,2457
2020-01-01,1,2,1,2020,1,1,1,3,52,2269
2020-01-01,2,2,1,2020,1,1,1,4,36,2215
2020-01-01,3,2,1,2020,1,1,1,3,72,2174
2020-01-01,4,2,1,2020,1,1,1,3,90,2472
...,...,...,...,...,...,...,...,...,...,...
2024-12-31,19,1,12,2024,366,1,4,3,43,4689
2024-12-31,20,1,12,2024,366,1,4,3,51,4331
2024-12-31,21,1,12,2024,366,1,4,3,40,4015
2024-12-31,22,1,12,2024,366,1,4,3,51,3353
2024-12-31,23,1,12,2024,366,1,4,6,59,3219

In [48]:
#given date is weekend or not
data.insert(7,'is_weekend', data.index.dayofweek.isin([5,6]).astype(int))
data

,hour,dayofweek,month,year,dayofyear,weekofyear,quarter,is_weekend,Temperature,Humidity,Demand
Timestamp,,,,,,,,,,,
2020-01-01,0,2,1,2020,1,1,1,0,3,61,2457
2020-01-01,1,2,1,2020,1,1,1,0,3,52,2269
2020-01-01,2,2,1,2020,1,1,1,0,4,36,2215
2020-01-01,3,2,1,2020,1,1,1,0,3,72,2174
2020-01-01,4,2,1,2020,1,1,1,0,3,90,2472
...,...,...,...,...,...,...,...,...,...,...,...
2024-12-31,19,1,12,2024,366,1,4,0,3,43,4689
2024-12-31,20,1,12,2024,366,1,4,0,3,51,4331
2024-12-31,21,1,12,2024,366,1,4,0,3,40,4015
2024-12-31,22,1,12,2024,366,1,4,0,3,51,3353
2024-12-31,23,1,12,2024,366,1,4,0,6,59,3219